name: Update HTML List
on:
  push:
    branches: [ main ]  # 在 main 分支推送时触发
    paths:
      - '*.html'       # 仅当 HTML 文件变动时运行

jobs:
  update-html-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate HTML file list
        id: generate-list
        run: |
          # 获取所有 HTML 文件（排除 suiji.html）
          HTML_FILES=$(find . -name "*.html" ! -name "suiji.html" | sed 's|^./||')

          # 转换为 GitHub Pages URL
          REPO_URL="https://pa-kos.github.io/vid2/"
          HTML_URLS=$(echo "$HTML_FILES" | awk -v url="$REPO_URL" '{print url $0}')

          # 格式化为 JavaScript 数组（单行）
          JS_ARRAY="[$(echo "$HTML_URLS" | sed "s/^/'/;s/$/'/" | tr '\n' ',' | sed 's/,$//')]"

          # 输出到环境变量
          echo "html_files=${JS_ARRAY}" >> $GITHUB_OUTPUT

      - name: Update suiji.html
        run: |
          # 替换 htmlFiles 数组
          sed -i "s|let htmlFiles = .*;|let htmlFiles = ${{ steps.generate-list.outputs.html_files }};|" suiji.html

          # 提交更改
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add suiji.html
          git commit -m "[Automated] Update HTML file list"
          git push
